"""This is Data Models Module. It defines all data structures that are used in the application.
They are used to standardize the data flow pipeline."""
from datetime import datetime
from enum import Enum
from typing import List, Optional
from pydantic import BaseModel, Field

class TopicEnum(str, Enum):
    """This enum defines the possible topics for news articles."""
    POLITICS = 'Politics'
    TECH = 'Tech'
    SPORTS = 'Sports'
    BUSINESS = 'Business'
    HEALTH = 'Health'
    SCIENCE = 'Science'
    WORLD = 'World'
    ENTERTAINMENT = 'Entertainment'
    OTHER = 'Other'

class SentimentEnum(str, Enum):
    """This enum defines the possible sentiments for news articles."""
    POSITIVE = 'positive'
    NEGATIVE = 'negative'
    NEUTRAL = 'neutral'

class Source(BaseModel):
    """This class shows a news source.
    Attributes are:
        - name: Name of the news source.
        - url: Web link to the news source.
        - is_html_scrape: Boolean indicating if the source is scraped from HTML or RSS feed.
    """
    name: str
    url: str
    is_html_scrape: bool = False

class Article(BaseModel):
    """This class shows a raw news article taken from RSS feeds or HTML sources.
    Attributes are:
        - id: Unique identifier of the article.
        - title: Title of the article.
        - content: Content of the article.
        - url: Web link to the news source.
        - source: Name of the news source.
        - published_at: Date and time when the article was published.
        - raw_html: Raw HTML content of the article.
    """
    id: str
    title: str
    content: str
    url: str
    source: str
    published_at: datetime
    raw_html: Optional[str] = None
    canonical_url: Optional[str] = None
    content_hash: Optional[str] = None

class LabeledSummary(BaseModel):
    """This class shows a labeled summary of a news article.
    Attributes are:
        - summary: This is the summary of the article, which is generated by AI.
        - topic: This is the topic of the article, which is used for categorization and filtering.
        - sentiment: This is the sentiment of the article, which is used for sentiment analysis.
    """
    summary: str
    topic: TopicEnum
    sentiment: SentimentEnum

class ProcessedArticle(BaseModel):
    """It shows a processed article ready for AI, with clean text and no duplicates
    Attributes are:
        - article_id: This is the reference ID which points to the original article.
        - cleaned_content: This is the cleaned content of the article, with no HTML tags or special characters.
        - embedding: This is the vector representation of the cleaned content. It is used for semantic search and AI processing.
        - cluster_id: This is the cluster ID which groups similar articles together. It is used for clustering and topic modeling.
    """
    article_id: str
    article: Article
    labeled_summary: Optional[LabeledSummary] = None
    embedding: List[float] = Field(default_factory=list)

class BriefingItem(BaseModel):
    """This class shows a final version AI-generated news summary
    Attributes are:
        - title: AI-generated title.
        - summary: Bullet points of the article.
        - topic: The topic of the article, which is used for categorization and filtering.
        - source_urls: List of original reference links.
        - relevance_score: How well this news matches user interests (0.0 to 1.0).
    """
    title: str
    summary: str
    topic: TopicEnum
    relevance_score: float
    source_urls: List[str] = Field(default_factory=list)

class User(BaseModel):
    """This class shows a user profile with their interests and preferences.
    Attributes are:
        - user_id: Unique identifier of the user.
        - topics: List of topics the user is interested in.
        - preferred_length: Preferred length of the news summary ('short', 'medium', 'long').
    """
    user_id: str
    preferred_topics: List[TopicEnum] = Field(default_factory=list)
    excluded_sources: List[str] = Field(default_factory=list)
    preferred_length: str = 'medium'